### ISSUE TITLE
Experiment URN required when creating a new meta-analysis score set

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#58] opened 2023-05-22 04:53 UTC
The record fails to validate when a score set doesn't have an experiment specified. However, meta-analysis score sets get their own experiment (and sometimes their own experiment set) when created so it's not possible to provide this at creation time.

**Comment by jstone-uw** [comment] 2023-06-15 03:04
I added the following logic that we discussed:

- An experiment URL must be provided when the score set is not a meta-analysis, and it must not be provided when the score set is a meta-analysis.

- When creating a meta-analysis, the API looks for any existing meta-analysis with the same set of underlying source score sets.
  - If one exists, it assigns the new meta-analysis to the same experiment.
  - Otherwise, it creates a new experiment using the score set's title, short description, abstract, and methods (but not its extra JSON metadata).

**Comment by jstone-uw** [comment] 2023-06-15 03:05
Some conditions can arise that seem unusual at first glance. For instance, consider this scenario:

1.  User A creates meta-analysis tmp:1 for score sets X and Y, in new experiment tmp:a.
2. User B creates another meta-analysis, tmp:2, for the same score sets X and Y. It gets assigned to the same unpublished experiment tmp:a.
3. User B publishes score set tmp:2.

Experiment tmp:a is now published as urn:1, with one published score set (tmp:2, now urn:1.1). Experiment 1 was created by user A, whose score set is still unpublished.

I don't think this results in any real data inconsistency; user A can still publish tmp:1 as score set urn:1.2. The result is that we never find two experiments containing meta-analyses for the same collection of underlying score sets, as desired. But it may be worthwhile to hide a meta-analysis experiment's creator, since by design it may include score sets created by multiple users.

**Comment by jstone-uw** [comment] 2023-06-15 03:11
The validation described above occurs in a Pydantic root validator, i.e. one that is not associated with a specific field. As a result, validation errors for missing experiments will not currently cause the UI to highlight the experiment input. A UI update is needed to display errors not associated with particular fields, to support this and other use cases.

**Comment by jstone-uw** [comment] 2023-06-15 05:59
I'll make a separate story about unit tests for meta-analyses, by the way.

**Closed** 2023-07-04 02:40 UTC
Labels: bug
