### ISSUE TITLE
MaveDB IDs are reported using the tmp: namespace

### ISSUE THREAD

**Issue by jarbesfeld** [VariantEffect/mavedb-api#326] opened 2024-10-02 21:09 UTC
When running queries using the /scores endpoint, a MaveDB ID starting with the prefix `tmp:` is reported. I believe the prefix should be urn:mavedb:{score set number)#{variant number)

**Comment by bencap** [comment] 2024-10-03 19:54
Thanks for reporting @jarbesfeld. we have this planned as part of #281 and should get to it within a couple of weeks.

**Comment by bencap** [comment] 2024-10-17 17:12
Closing as a duplicate of #281, this issue can be tracked using that issue page.

**Closed by bencap** 2024-10-17 17:12 UTC
Labels: type: bug, core: duplicate, app: backend
