### ISSUE TITLE
Score/count processing sometimes hangs

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#231] opened 2024-06-16 23:56 UTC
When uploading a dataset yesterday, I noticed that the page didn't progress past the "Scores and/or counts are being processed. Refresh this page in a few minutes to check on their status." step for some time. I edited the score set and re-uploaded the file, and then it progressed very quickly.

I'm not sure what's causing this intermittent behavior under the hood as I didn't see any output in the monitoring channel, but maybe as a stopgap we could add something to that error message that instructs users to try uploading the score table again if it doesn't progress after an hour or so.

**Comment by bencap** [comment] 2024-10-07 23:49
Likely caused by something similar to #308, which should enable these score sets to get marked as failed.

**Closed by bencap** 2024-10-07 23:49 UTC
Labels: type: bug, app: backend, app: worker
