### ISSUE TITLE
Async Variant Additions for Score Sets

### ISSUE THREAD

**Issue by bencap** [VariantEffect/mavedb-api#160] opened 2024-03-01 21:33 UTC
In support of issues like https://atlasofvarianteffect.slack.com/archives/C06A73QAFK4/p1709230987644889, we should handle variant additions to score sets via some sort of worker process handled asynchronously to score set creation. 

Completion of this task would also involve setting up a new worker service for MaveDB and enabling it to handle async creation of variants. Any errors during variant creation should be served to the user on the score set page.

**Comment by jstone-uw** [comment] 2024-03-24 17:38
Duplicate of #90

**Closed by jstone-uw** 2024-03-24 17:38 UTC
